saleor/dashboard/category/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.category_list, name='category-list'),
    url(r'^(?P<root_pk>[0-9]+)/$',
        views.category_list, name='category-list'),
    url(r'^add/$',
        views.category_create, name='category-add'),
    url(r'^(?P<root_pk>[0-9]+)/add/$',
        views.category_create, name='category-add'),
    url(r'^(?P<root_pk>[0-9]+)/edit/$',
        views.category_edit, name='category-edit'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.category_delete, name='category-delete')
]

saleor/dashboard/customer/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.customer_list, name='customers'),
    url(r'^(?P<pk>[0-9]+)/$', views.customer_details, name='customer-details')
]

saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.OrderListView.as_view(), name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$', views.orderline_change_quantity,
        name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$', views.orderline_split,
        name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$', views.ship_delivery_group,
        name='ship-delivery-group')
]

saleor/dashboard/product/urls.py
from django.conf.urls import url

from . import api
from . import views


urlpatterns = [
    url(r'^$',
        views.product_list, name='product-list'),
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.product_edit, name='product-update'),
    url(r'^add/$',
        views.product_create, name='product-add'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.product_delete, name='product-delete'),

    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$',
        views.variant_edit, name='variant-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/add/$',
        views.variant_edit, name='variant-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$',
        views.variant_delete, name='variant-delete'),
    url(r'^(?P<product_pk>[0-9]+)/variants/bulk_delete/',
        views.variants_bulk_delete, name='variant-bulk-delete'),

    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/$',
        views.stock_edit, name='product-stock-update'),
    url(r'^(?P<product_pk>[0-9]+)/stock/add/$',
        views.stock_edit, name='product-stock-add'),
    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/delete/$',
        views.stock_delete, name='product-stock-delete'),
    url(r'^(?P<product_pk>[0-9]+)/stock/bulk_delete/',
        views.stock_bulk_delete, name='stock-bulk-delete'),

    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$',
        views.product_image_edit, name='product-image-update'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$',
        views.product_image_edit, name='product-image-add'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$',
        views.product_image_delete, name='product-image-delete'),
    url('^(?P<product_pk>[0-9]+)/images/reorder/$',
        api.reorder_product_images, name='product-images-reorder'),
    url('^(?P<product_pk>[0-9]+)/images/upload/$',
        api.upload_image, name='product-images-upload'),

    url(r'attributes/$',
        views.attribute_list, name='product-attributes'),
    url(r'attributes/(?P<pk>[0-9]+)/$',
        views.attribute_edit, name='product-attribute-update'),
    url(r'attributes/add/$',
        views.attribute_edit, name='product-attribute-add'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$',
        views.attribute_delete, name='product-attribute-delete'),
]

saleor/dashboard/urls.py
from django.conf.urls import url, include

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .customer.urls import urlpatterns as customer_urls
from .order.urls import urlpatterns as order_urls
from .payments.urls import urlpatterns as payments_urls
from .product.urls import urlpatterns as product_urls


urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^payments/', include(payments_urls)),
    url(r'^customers/', include(customer_urls)),
]

saleor/registration/urls.py
from django.conf.urls import patterns, url

from ..core import TOKEN_PATTERN
from . import views


urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^oauth_callback/(?P<service>\w+)/$', views.oauth_callback,
        name='oauth_callback'),
    url(r'^change_password/$', views.change_password,
        name='change_password'),
    url(r'^request_email_confirmation/$', views.request_email_confirmation,
        name='request_email_confirmation'),
    url(r'^confirm_email/%s/$' % (TOKEN_PATTERN,), views.confirm_email,
        name='confirm_email'),
    url(r'^request_email_change/$', views.request_email_change,
        name='request_email_change'),
    url(r'^change_email/%s/$' % (TOKEN_PATTERN,), views.change_email,
        name='change_email')
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap


from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .userprofile.urls import urlpatterns as userprofile_urls
from .dashboard.urls import urlpatterns as dashboard_urls


admin.autodiscover()

urlpatterns = [
    url(r'^$', include(core_urls), name='home'),
    url(r'^account/', include(registration_urls, namespace='registration')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^selectable/', include('selectable.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT})]

saleor/dashboard/category/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.utils.text import slugify
from unidecode import unidecode

from ...product.models import Category


class CategoryForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.parent_pk = kwargs.pop('parent_pk')
        super(CategoryForm, self).__init__(*args, **kwargs)
        if self.instance.parent and self.instance.parent.hidden:
            self.fields['hidden'].widget.attrs['disabled'] = True

    class Meta:
        model = Category
        exclude = ['slug']

    def save(self, commit=True):
        self.instance.slug = slugify(unidecode(self.instance.name))
        if self.parent_pk:
            self.instance.parent = get_object_or_404(Category, pk=self.parent_pk)
        if self.instance.parent and self.instance.parent.hidden:
            self.instance.hidden = True
        super(CategoryForm, self).save(commit=commit)
        self.instance.set_hidden_descendants(self.cleaned_data['hidden'])
        return self.instance

saleor/dashboard/category/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import ugettext_lazy as _

from ...product.models import Category
from ..views import staff_member_required
from .forms import CategoryForm


@staff_member_required
def category_list(request, root_pk=None):
    root = None
    path = None
    categories = Category.tree.root_nodes()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
        categories = root.get_children()
    ctx = {'categories': categories, 'path': path, 'root': root}
    return TemplateResponse(request, 'dashboard/category/list.html', ctx)


@staff_member_required
def category_create(request, root_pk=None):
    category = Category()
    form = CategoryForm(request.POST or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(request, _('Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    ctx = {'category': category, 'form': form}
    return TemplateResponse(request, 'dashboard/category/detail.html', ctx)


@staff_member_required
def category_edit(request, root_pk=None):
    category = get_object_or_404(Category, pk=root_pk)
    form = CategoryForm(request.POST or None, instance=category,
                        parent_pk=category.parent_id)
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(request, _('Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    elif form.errors:
        status = 400
    ctx = {'category': category, 'form': form, 'status': status}
    template = 'dashboard/category/modal_edit.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        messages.success(request, _('Deleted category %s') % category)
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {'redirectUrl': reverse(
                    'dashboard:category-list', kwargs={'root_pk': root_pk})}
                return JsonResponse(response)
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            if request.is_ajax():
                response = {'redirectUrl': reverse('dashboard:category-list')}
                return JsonResponse(response)
            return redirect('dashboard:category-list')
    ctx = {'category': category,
           'descendants': list(category.get_descendants()),
           'products_count': len(category.products.all())}
    return TemplateResponse(request,
                            'dashboard/category/modal_delete.html',
                            ctx)

saleor/dashboard/customer/views.py
from __future__ import unicode_literals

from django.db.models import Count, Max
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.utils.translation import ugettext_lazy as _

from .forms import CustomerSearchForm
from ..utils import paginate
from ..views import staff_member_required
from ...userprofile.models import User


@staff_member_required
def customer_list(request):
    customers = (
        User.objects
        .prefetch_related('orders', 'addresses')
        .select_related('default_billing_address', 'default_shipping_address')
        .annotate(
            num_orders=Count('orders', distinct=True),
            last_order=Max('orders', distinct=True)))

    form = CustomerSearchForm(request.GET or None, queryset=customers)
    form_values = [(field.name, field.value() or '') for field in form]
    if form.is_valid():
        customers = form.search()
    else:
        customers = customers.filter(
            orders__status__in=['new', 'payment-pending', 'fully-paid'])
    title = _('Results (%s)') % len(customers)

    customers, paginator = paginate(customers, 30, request.GET.get('page'))
    ctx = {'customers': customers, 'form': form, 'title': title,
           'paginator': paginator, 'default_pagination_params': form_values}
    return TemplateResponse(request, 'dashboard/customer/list.html', ctx)


@staff_member_required
def customer_details(request, pk):
    queryset = User.objects.prefetch_related(
        'orders', 'addresses').select_related('default_billing_address')
    customer = get_object_or_404(queryset, pk=pk)
    customer_orders = customer.orders.all()
    ctx = {'customer': customer, 'customer_orders': customer_orders}
    return TemplateResponse(request, 'dashboard/customer/detail.html', ctx)

saleor/dashboard/payments/views.py
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.views.generic import ListView
from payments.models import PAYMENT_STATUS_CHOICES

from ..views import (FilterByStatusMixin, StaffMemberOnlyMixin,
                     staff_member_required)
from ...order.models import Payment
from ..order.forms import PaymentFilterForm

class PaymentList(StaffMemberOnlyMixin, FilterByStatusMixin, ListView):
    model = Payment
    template_name = 'dashboard/payments/list.html'
    context_object_name = 'payments'
    paginate_by = 30
    form_class = PaymentFilterForm
    status_choices = PAYMENT_STATUS_CHOICES
    status_order = ['waiting', 'input', 'preauth', 'confirmed', 'refunded',
                    'rejected', 'error']

    def get_queryset(self):
        qs = super(PaymentList, self).get_queryset()
        return qs.order_by('-created').select_related('order')


@staff_member_required
def payment_details(request, pk):
    payment = get_object_or_404(Payment, pk=pk)
    return TemplateResponse(request, 'dashboard/payments/detail.html',
                            {'payment': payment})

saleor/dashboard/views.py
from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required \
    as _staff_member_required
from django.db.models import Q, Sum
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.views.generic.edit import FormMixin

from ..order.models import Order, Payment
from ..product.models import Product
from saleor.dashboard.order.forms import OrderFilterForm


def staff_member_required(f):
    return _staff_member_required(f, login_url='registration:login')


class StaffMemberOnlyMixin(object):
    @method_decorator(staff_member_required)
    def dispatch(self, *args, **kwargs):
        return super(StaffMemberOnlyMixin, self).dispatch(*args, **kwargs)


class FilterByStatusMixin(FormMixin):
    form_class = OrderFilterForm

    def __init__(self):
        super(FilterByStatusMixin, self).__init__()
        self.active_filter = None

    def get_queryset(self):
        queryset = super(FilterByStatusMixin, self).get_queryset()
        active_filter = self.request.GET.get('status')
        if active_filter:
            self.active_filter = active_filter
            queryset = queryset.filter(status=self.active_filter)
        return queryset

    def get_initial(self):
        initial = super(FilterByStatusMixin, self).get_initial()
        if self.active_filter:
            initial['status'] = self.active_filter
        return initial

    def get_context_data(self):
        ctx = super(FilterByStatusMixin, self).get_context_data()
        ctx['form'] = self.get_form()
        return ctx


@staff_member_required
def index(request):
    orders_to_ship = Order.objects.filter(status='fully-paid')
    orders_to_ship = (orders_to_ship
                      .select_related('user')
                      .prefetch_related('groups', 'groups__items', 'payments'))
    payments = Payment.objects.filter(status='preauth').order_by('-created')
    payments = payments.select_related('order', 'order__user')
    low_stock = get_low_stock_products()
    ctx = {'preauthorized_payments': payments, 'orders_to_ship': orders_to_ship,
           'low_stock': low_stock}
    return TemplateResponse(request, 'dashboard/index.html', ctx)


def get_low_stock_products():
    threshold = getattr(settings, 'LOW_STOCK_THRESHOLD', 10)
    products = Product.objects.annotate(total_stock=Sum('variants__stock__quantity'))
    return products.filter(Q(total_stock__lte=threshold)).distinct()

saleor/dashboard/templates/dashboard/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html class="no-js">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">

    <title>{% block title %}{% trans "Dashboard - Saleor" %}{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static "css/dashboard.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "versatileimagefield/css/versatileimagefield.css" %}">

    <script src="{% static "js/dashboard-head.js" %}"></script>
    {% block custom_css %}
    {% endblock %}
</head>

<body class="{% block body_class %}body-home{% endblock %}">
    <header class="header">
        <nav class="top-nav">
            <div class="container">
                <div class="nav-wrapper">
                    {% block header_menu %}
                        <a href="#" data-activates="side-menu" class="button-collapse header-button"><i class="mdi-navigation-menu"></i></a>
                    {% endblock %}
                    {% block breadcrumbs %}
                        <ul class="breadcrumbs">
                            <li>{% trans "Dashboard" %}</li>
                        </ul>
                    {% endblock %}
                    {% block header_extra %}{% endblock %}
                </div>
            </div>
            <ul class="side-nav fixed" id="side-menu">
                <li class="side-nav-user">
                    <ul class="collapsible collapsible-accordion">
                        <li>
                            <a class="waves-effect waves-teal collapsible-header">
                                <i class="mdi-action-account-circle"></i>{{ request.user }} <i class="mdi-navigation-arrow-drop-down"></i>
                            </a>
                            <div class="collapsible-body">
                                <ul>
                                    <li><a href="/" class="waves-effect waves-teal">{% trans "Visit storefront" %}</a></li>
                                    <li><a href="{% url 'registration:logout' %}" class="waves-effect waves-teal">{% trans "Log out" %}</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="brand-logo">
                    <a href="{% url 'dashboard:index' %}">
                        <img src="{% static "img/dashboard-logo.svg" %}" alt="Saleor">
                    </a>
                </li>
                <li class="nav-home"><a href="{% url 'dashboard:index' %}">Home</a></li>
                <li>
                    <ul class="collapsible collapsible-accordion" data-collapsible="accordion">
                        <li>
                            <a class="waves-effect waves-teal collapsible-header{% block menu_catalogue_class %}{% endblock %}">{% trans "Catalogue" %}</a>
                            <div class="collapsible-body">
                                <ul>
                                    <li class="subnav-products"><a href="{% url 'dashboard:product-list' %}">{% trans "Products" %}</a></li>
                                    <li class="subnav-attributes"><a href="{% url 'dashboard:product-attributes' %}">{% trans "Attributes" %}</a></li>
                                    <li class="subnav-categories"><a href="{% url 'dashboard:category-list' %}">{% trans "Categories" %}</a></li>
                                </ul>
                            </div>
                        </li>

                        <li class="divider"></li>

                        <li>
                            <a class="waves-effect waves-teal collapsible-header{% block menu_sales_class %}{% endblock %}">{% trans "Sales" %}</a>
                            <div class="collapsible-body">
                                <ul>
                                    <li class="subnav-orders"><a href="{% url 'dashboard:orders' %}">{% trans "Orders" %}</a></li>
                                    <li class="subnav-customers"><a href="{% url 'dashboard:customers' %}">{% trans "Customers" %}</a></li>
                                    <li class="subnav-payments"><a href="{% url 'dashboard:payments' %}">{% trans "Payments" %}</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </header>

    <main class="main">
        <div class="container">
            {% include "dashboard/includes/_messages.html" %}

            {% block content %}
            {% endblock %}
        </div>
    </main>

    <div class="hide-on-med-only"></div>
    <div class="hide-on-large-only"></div>
    <div id="base-modal" class="modal"></div>
    <div id="base-modal-fixed" class="modal modal-fixed-footer"></div>

    <!-- Core Scripts - Include with every page -->
    <script src="{% static "js/dashboard.js" %}"></script>
    <script src="{% static "versatileimagefield/js/versatileimagefield.js" %}"></script>

    {% block custom_js %}{% endblock %}
</body>
</html>

saleor/dashboard/templates/dashboard/index.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load prices_i18n %}

{% block title %}{{ block.super }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col s12">
        <div class="card">
            <div class="data-table-header{% if not preauthorized_payments %} data-table-header--no-data{% endif %}">
                <span class="card-title black-text">{% trans "Preauthorized payments" %}</span>
            </div>

            {% if preauthorized_payments %}
                <div class="data-table-container">
                    <table class="bordered hoverable responsive data-table">
                        <thead>
                            <tr>
                                <th>{% trans "Order number" %}</th>
                                <th>{% trans "Date" %}</th>
                                <th>{% trans "Customer" %}</th>
                                <th class="text-right">{% trans "Amount" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for payment in preauthorized_payments %}
                                <tr>
                                    <td><a href="{% url "dashboard:order-details" order_pk=payment.order.pk %}">{{ payment.order }}</a></td>
                                    <td>{{ payment.created }}</td>
                                    <td>{{ payment.order.user|default:_("Guest") }}</td>
                                    <td class="text-right">{% gross payment.get_total_price %}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="card-content card-content--no-data">
                    <p>{% trans "No preauthorized payments." %}</p>
                </div>
            {% endif %}
        </div>

        <div class="card">
            <div class="data-table-header{% if not orders_to_ship %} data-table-header--no-data{% endif %}">
                <span class="card-title black-text">{% trans "Orders ready for shipment" %}</span>
            </div>

            {% if orders_to_ship %}
                {% include "dashboard/includes/_orders_table.html" with orders=orders_to_ship %}
            {% else %}
                <div class="card-content card-content--no-data">
                    <p>{% trans "No orders are ready for shipment." %}</p>
                </div>
            {% endif %}
        </div>

        <div class="card">
            <div class="card-content">
                <span class="card-title black-text">{% trans "Products with low stock" %}</span>

                {% if low_stock %}
                    <ul class="list">
                        {% for product in low_stock %}
                            <li class="list-item">
                                <a class="list-item-name list-item-name--single" href="{% url "dashboard:product-update" pk=product.pk %}#stock">
                                    {{ product }} ({{ product.total_stock }})
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>{% trans "No products are low in stock." %}</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}